type: entities
show_header_toggle: false
title: Settings
style:
    .: |
        ha-card {
            --ha-card-box-shadow: none;
            background-color: rgba(0,0,0,0.35);
            border-radius: 15px;
            "--primary-text-color": "#f2f2f2";
            "--paper-card-background-color": 'rgba(0, 0, 0,0.65)';
            font-weight: bold;
            font-size: 1.55em;
            text-transform: capitalize;
            font-variant: small-caps;
            text-shadow: "1px 1px 2px black, 0 0 25px green, 0 0 5px darkgreen";
            "--paper-item-icon-color": lime;
            "--iron-icon-stroke-color": green;
            "--iron-icon-height": 41px;
            "--iron-icon-width": 41px;
            margin-top: 5px;
        }
entities:
  - input_select.mobile_wallpaper
  - input_select.auto_borderz
  - input_select.auto_cornerz
