type: custom:auto-entities
card:
  type: entities
  title: Wifi
filter:
    include:
    - entity_id: sensor.*wifi*
    exclude:
    - entity_id: sensor.*A520*
    - entity_id: sensor.*G970*
    - entity_id: sensor.*connection*
sort:
    method: name
