---
 # input_boolean.tablet_automations
title: 'Automations settings'
large: true
hide_header: true
style:
  $: |
    .mdc-dialog .mdc-dialog__container {
      width: 100%;
    }
    .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
      width:100%;
      box-shadow:none;
    }
      
  .: |
    :host {
      --mdc-theme-surface: rgba(0,0,0,0);
      --secondary-background-color: rgba(0,0,0,0);
      --ha-card-background: rgba(0,0,0,0);
      --mdc-dialog-scrim-color: rgba(0,0,0,0.8);
      --mdc-dialog-min-height: 100%;
      --mdc-dialog-min-width: 100%;
      --mdc-dialog-max-width: 100%;          
    }
    mwc-icon-button {
      color: #FFF;
    }
card:
  type: custom:vertical-stack-in-card
  cards:
    - type: horizontal-stack
      cards:
        - type: vertical-stack
          cards:
            - !include /config/lovelace/cards/clock.yaml
            - !include /config/lovelace/cards/VMC.yaml
        - type: vertical-stack
          cards:
            - !include /config/lovelace/cards/automations_config.yaml
