---
 # input_boolean.computer_settings
title: 'Automations settings'
large: true
hide_header: true
style:
  $: |
    .mdc-dialog .mdc-dialog__container {
      width: 100%;
      background: url("/local/images-lovelace/background/{{ states.input_select.compu_wallpaper.state }}.jpg");
      background-repeat: no-repeat;
      background-size: 100% 100%;
      border-radius: {{ states.input_select.auto_cornerz.state }};
      border: solid 3px {{ states.input_select.auto_borderz.state }};
    }
    .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
      width:100%;
      box-shadow:none;
    }
      
  .: |
    :host {
      --mdc-theme-surface: rgba(0,0,0,0);
      --secondary-background-color: rgba(0,0,0,0);
      --ha-card-background: rgba(0,0,0,0);
      --mdc-dialog-scrim-color: rgba(0,0,0,0.8);
      --mdc-dialog-min-height: 100%;
      --mdc-dialog-min-width: 100%;
      --mdc-dialog-max-width: 100%;  
    
    }
    mwc-icon-button {
      color: #FFF;
    }
card:
    type: entities
    style:
      .: |
        .card-content {
          "--primary-text-color": "#F2F2F2";
          "--paper-item-icon-color": rgb(19, 235, 19);
          "--paper-item-icon-active-color": rgb(255, 255, 0);
          "--iron-icon-height": 45px;
          "--iron-icon-width": 45px;
          "--app-toolbar-font-size": 1.3em;
          animation: blink 2s linear infinite;
          box-sizing: border-box;
        }
      
    entities:  
    - type: custom:vertical-stack-in-card
      cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - !include /config/lovelace/cards/clock.yaml
              - !include /config/lovelace/cards/VMC.yaml
          - type: vertical-stack
            cards:
              - !include /config/lovelace/cards/automations_config.yaml
              #- !include /config/lovelace/cards/automations.yaml
          - type: vertical-stack
            cards:
              #- !include /config/lovelace/cards/script.yaml
              - !include /config/lovelace/cards/automations.yaml
          
          